Bump to icedtea-3.1.0pre03.
Upstream changes:
  - PR1958: GTKLookAndFeel does not honor gtk-alternative-button-order
  - PR2931, G478960: Provide Infinality Support via fontconfig
  - PR2974: PKCS#10 certificate requests now use CRLF line endings rather than system line endings
  - PR3083, RH1346460: Regression in SSL debug output without an ECC provider
  - S6260348, PR3066: GTK+ L&F JTextComponent not respecting desktop caret blink rate
  - S6778087, PR1061: getLocationOnScreen() always returns (0, 0) for mouse wheel events
  - S6961123, PR2972: setWMClass fails to null-terminate WM_CLASS string
  - S8008657, PR3077: JSpinner setComponentOrientation doesn't affect on text orientation
  - S8014212, PR2866: Robot captures black screen
  - S8029339, PR1061: Custom MultiResolution image support on HiDPI displays
  - S8031145, PR3077: Re-examine closed i18n tests to see it they can be moved to the jdk repository.
  - S8038631, PR3077: Create wrapper for awt.Robot with additional functionality
  - S8039279, PR3077: Move awt tests to openjdk repository
  - S8041561, PR3077: Inconsistent opacity behaviour between JCheckBox and JRadioButton
  - S8041592, PR3077: [TEST_BUG] Move 42 AWT hw/lw mixing tests to jdk
  - S8041915, PR3077: Move 8 awt tests to OpenJDK regression tests tree
  - S8043126, PR3077: move awt automated functional tests from AWT_Events/Lw and AWT_Events/AWT to OpenJDK repository
  - S8043131, PR3077: Move ShapedAndTranslucentWindows and GC functional AWT tests to regression tree
  - S8044157, PR3077: [TEST_BUG] Improve recently submitted AWT_Mixing tests
  - S8044172, PR3077: [TEST_BUG] Move regtests for 4523758 and AltPlusNumberKeyCombinationsTest to jdk
  - S8044429, PR3077: move awt automated tests for AWT_Modality to OpenJDK repository
  - S8044762, PR2960: com/sun/jdi/OptionTest.java test time out
  - S8044765, PR3077: Move functional tests AWT_SystemTray/Automated to openjdk repository
  - S8047180, PR3077: Move functional tests AWT_Headless/Automated to OpenJDK repository
  - S8047367, PR3077: move awt automated tests from AWT_Modality to OpenJDK repository - part 2
  - S8048246, PR3077: Move AWT_DnD/Clipboard/Automated functional tests to OpenJDK
  - S8049226, PR2960: com/sun/jdi/OptionTest.java test times out again
  - S8049617, PR3077: move awt automated tests from AWT_Modality to OpenJDK repository - part 3
  - S8049694, PR3077: Migrate functional AWT_DesktopProperties/Automated tests to OpenJDK
  - S8050885, PR3077: move awt automated tests from AWT_Modality to OpenJDK repository - part 4
  - S8051440, PR3077: move tests about maximizing undecorated to OpenJDK
  - S8052012, PR3077: move awt automated tests from AWT_Modality to OpenJDK repository - part 5
  - S8052408, PR3077: Move AWT_BAT functional tests to OpenJDK (3 of 3)
  - S8053657, PR3077: [TEST_BUG] move some 5 tests related to undecorated Frame/JFrame to JDK
  - S8054143, PR3077: move awt automated tests from AWT_Modality to OpenJDK repository - part 6
  - S8054358, PR3077: move awt automated tests from AWT_Modality to OpenJDK repository - part 7
  - S8054359, PR3077: move awt automated tests from AWT_Modality to OpenJDK repository - part 8
  - S8055360, PR3077: Move the rest part of AWT ShapedAndTranslucent tests to OpenJDK
  - S8055664, PR3077: move 14 tests about setLocationRelativeTo to jdk
  - S8055836, PR3077: move awt tests from AWT_Modality to OpenJDK repository - part 9
  - S8056911, PR3077: Remove internal API usage from ExtendedRobot class
  - S8057694, PR3077: move awt tests from AWT_Modality to OpenJDK repository - part 10
  - S8058959, PR1061: closed/java/awt/event/ComponentEvent/MovedResizedTwiceTest/MovedResizedTwiceTest.java failed automatically
  - S8062606, PR3077: Fix a typo in java.awt.Robot class
  - S8063102, PR3077: Change open awt regression tests to avoid sun.awt.SunToolkit.realSync, part 1
  - S8063104, PR3077: Change open awt regression tests to avoid sun.awt.SunToolkit.realSync, part 2
  - S8063106, PR3077: Change open swing regression tests to avoid sun.awt.SunToolkit.realSync, part 1
  - S8063107, PR3077: Change open swing regression tests to avoid sun.awt.SunToolkit.realSync, part 2
  - S8064573, PR3077: [TEST_BUG] javax/swing/text/AbstractDocument/6968363/Test6968363.java is asocial pressing VK_LEFT and not releasing
  - S8064575, PR3077: [TEST_BUG] javax/swing/JEditorPane/6917744/bug6917744.java 100 times press keys and never releases
  - S8064809, PR3077: [TEST_BUG] javax/swing/JComboBox/4199622/bug4199622.java contains a lot of keyPress and not a single keyRelease
  - S8067441, PR3077: Some tests fails with error: cannot find symbol getSystemMnemonicKeyCodes()
  - S8068228, PR3077: Test closed/java/awt/Mouse/MaximizedFrameTest/MaximizedFrameTest fails with GTKLookAndFeel
  - S8069361, PR1061: SunGraphics2D.getDefaultTransform() does not include scale factor
  - S8073320, PR1061: Windows HiDPI Graphics support
  - S8074807, PR3077: Fix some tests unnecessary using internal API
  - S8076315, PR3077: move 4 manual functional swing tests to regression suite
  - S8129822, PR3077: Define "headful" jtreg keyword
  - S8132123, PR1061: MultiResolutionCachedImage unnecessarily creates base image to get its size
  - S8133539, PR1061: [TEST_BUG] Split java/awt/image/MultiResolutionImageTest.java in two to allow restricted access
  - S8137571, PR1061: Linux HiDPI Graphics support
  - S8142406, PR1061: [TEST] MultiResolution image: need test to cover the case when @2x image is corrupted
  - S8145188, PR2945: No LocalVariableTable generated for the entire JDK
  - S8145320, PR3078: Create unsafe_arraycopy and generic_arraycopy for AArch64
  - S8145547, PR1061: [AWT/Swing] Conditional support for GTK 3 on Linux
  - S8148328, PR3078: aarch64: redundant lsr instructions in stub code.
  - S8148783, PR3078: aarch64: SEGV running SpecJBB2013
  - S8148948, PR3078: aarch64: generate_copy_longs calls align() incorrectly
  - S8149080, PR3078: AArch64: Recognise disjoint array copy in stub code
  - S8149365, PR3078: aarch64: memory copy does not prefetch on backwards copy
  - S8149907, PR3078: aarch64: use load/store pair instructions in call_stub
  - S8150038, PR3078: aarch64: make use of CBZ and CBNZ when comparing narrow pointer with zero
  - S8150045, PR3078: arraycopy causes segfaults in SATB during garbage collection
  - S8150082, PR3078: aarch64: optimise small array copy
  - S8150229, PR3078: aarch64: pipeline class for several instructions is not set correctly
  - S8150258, PR1061: [TEST] HiDPI: create a test for multiresolution menu items icons
  - S8150313, PR3078: aarch64: optimise array copy using SIMD instructions
  - S8150394, PR3078: aarch64: add support for 8.1 LSE CAS instructions
  - S8150724, PR1061: [TEST] HiDPI: create a test for multiresolution icons
  - S8150844, PR1061: [hidpi] [macosx] -Dsun.java2d.uiScale should be taken into account for OS X
  - S8151340, PR3078: aarch64: prefetch the destination word for write prior to ldxr/stxr loops.
  - S8151502, PR3078: optimize pd_disjoint_words and pd_conjoint_words
  - S8151775, PR3078: aarch64: add support for 8.1 LSE atomic operations
  - S8151841, PR2882: Build needs additional flags to compile with GCC 6
  - S8151841, PR2882: Build needs additional flags to compile with GCC 6 [plus parts of 8032045]
  - S8151841, PR2882: Build needs additional flags to compile with GCC 6 [plus parts of 8034788 & 8149647]
  - S8152537, PR3078: aarch64: Make use of CBZ and CBNZ when comparing unsigned values with zero.
  - S8152840, PR3078: aarch64: improve _unsafe_arraycopy stub routine
  - S8153713, PR3078: aarch64: improve short array clearing using store pair
  - S8153797, PR3078: aarch64: Add Arrays.fill stub code
  - S8154537, PR3078: AArch64: some integer rotate instructions are never emitted
  - S8154739, PR3078: AArch64: TemplateTable::fast_xaccess loads in wrong mode
  - S8155015, PR3078: Aarch64: bad assert in spill generation code
  - S8155100, PR3078: AArch64: Relax alignment requirement for byte_map_base
  - S8155612, PR3078: Aarch64: vector nodes need to support misaligned offset
  - S8155613, PR1061: [PIT] crash in AWT_Desktop/Automated/Exceptions/BasicTest
  - S8155617, PR3078: aarch64: ClearArray does not use DC ZVA
  - S8155653, PR3078: TestVectorUnalignedOffset.java not pushed with 8155612
  - S8156020, PR1061: 8145547 breaks AIX and and uses RTLD_NOLOAD incorrectly
  - S8156128, PR1061: Tests for [AWT/Swing] Conditional support for GTK 3 on Linux
  - S8156731, PR3078: aarch64: java/util/Arrays/Correct.java fails due to _generic_arraycopy stub routine
  - S8157841, PR3078: aarch64: prefetch ignores cache line size
  - S8157906, PR3078: aarch64: some more integer rotate instructions are never emitted
  - S8158260, PR2991, RH1341258: PPC64: unaligned Unsafe.getInt can lead to the generation of illegal instructions
  - S8158913, PR3078: aarch64: SEGV running Spark terasort
  - S8159052, PR3078: aarch64: optimise unaligned copies in pd_disjoint_words and pd_conjoint_words
  - S8159063, PR3078: aarch64: optimise unaligned array copy long
  - S8159244, PR3074: Partially initialized string object created by C2's string concat optimization may escape
  - S8159690, PR3077: [TESTBUG] Mark headful tests with @key headful.

ChangeLog:

2016-07-13  Andrew John Hughes  <gnu_andrew@member.fsf.org>

	Bump to icedtea-3.1.0pre03.
	* Makefile.am:
	(CORBA_CHANGESET): Update to icedtea-3.1.0pre03 tag.
	(JAXP_CHANGESET): Likewise.
	(JAXWS_CHANGESET): Likewise.
	(JDK_CHANGESET): Likewise.
	(LANGTOOLS_CHANGESET): Likewise.
	(OPENJDK_CHANGESET): Likewise.
	(NASHORN_CHANGESET): Likewise.
	(CORBA_SHA256SUM): Likewise.
	(JAXP_SHA256SUM): Likewise.
	(JAXWS_SHA256SUM): Likewise.
	(JDK_SHA256SUM): Likewise.
	(LANGTOOLS_SHA256SUM): Likewise.
	(OPENJDK_SHA256SUM): Likewise.
	(NASHORN_SHA256SUM): Likewise.
	* NEWS: Updated.
	* configure.ac: Bump to 3.1.0pre03.
	* hotspot.map.in: Update to icedtea-3.1.0pre03 tag.