Bump to icedtea-3.0.0pre04.
Upstream changes:
  - PR1413: Undefined reference to libz during link of unpack200
  - PR1869: Avoid x86 workaround when running Zero rather than a JIT
  - PR1937: Add configure option for -Werror
  - PR1975: SystemTap probes for the garbage collector.
  - PR2095, RH1163501: 2048-bit DH upper bound too small for Fedora infrastructure
  - PR2237, RH1194378: ppc64le should report its os.arch as ppc64le so tools can detect it
  - PR2400, RH1206656: Zero JVM crashes on startup when built with GCC 5
  - S4890063, PR2304, RH1214835: HPROF: default text truncated when using doe=n option
  - S6584008, PR2192, RH1173326: jvmtiStringPrimitiveCallback should not be invoked when string value is null
  - S6991580, PR2403: IPv6 Nameservers in resolv.conf throws NumberFormatException
  - S8067231, PR2401: Zero builds fails after JDK-6898462
  - S8067364, PR2146, RH114622: Printing to Postscript doesn't support dieresis
  - S8069072, PR1961, RH1135504: GHASH performance improvement
  - S8071705. PR2399, RH1182694: Java application menu misbehaves when running multiple screen stacked vertically
  - S8072385, PR2404: Only the first DNSName entry is checked for endpoint identification
  - S8074312, PR2253: Enable hotspot builds on 4.x Linux kernels
  - S8074859, PR1937: Turn on warnings as error
  - S8076212, PR2402: AllocateHeap() and ReallocateHeap() should be inlined.
  - S8078482, PR2398, RH1201393: ppc: pass thread to throw_AbstractMethodError
  - S8078654, PR2332: CloseTTFontFileFunc callback should be removed
  - S8078666, PR2325: JVM fastdebug build compiled with GCC 5 asserts with "widen increases"

2015-06-08  Andrew John Hughes  <gnu_andrew@member.fsf.org>

	* Makefile.am:
	(CORBA_CHANGESET): Update to icedtea-3.0.0pre04 tag.
	(JAXP_CHANGESET): Likewise.
	(JAXWS_CHANGESET): Likewise.
	(JDK_CHANGESET): Likewise.
	(LANGTOOLS_CHANGESET): Likewise.
	(OPENJDK_CHANGESET): Likewise.
	(NASHORN_CHANGESET): Likewise.
	(CORBA_SHA256SUM): Likewise.
	(JAXP_SHA256SUM): Likewise.
	(JAXWS_SHA256SUM): Likewise.
	(JDK_SHA256SUM): Likewise.
	(LANGTOOLS_SHA256SUM): Likewise.
	(OPENJDK_SHA256SUM): Likewise.
	(NASHORN_SHA256SUM): Likewise.
	* NEWS: Updated.
	* configure.ac: Bump to 3.0.0pre04.
	* hotspot.map: Update to icedtea-3.0.0pre04 tag.